version: '3.8'
services:
  entrersortie:
    container_name: entrersortie
    image: perce26/entrersortie:entrersortie
    restart: always
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_DATABASE: entrer-sortie
    depends_on:
      - db

    # volumes:
    #   - .:/usr/src/app