version: '3.8'
services:
  la_capitale:
    container_name: la_capitale
    image: perce26/entrersortie:la_capitale
    restart: always
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_DATABASE: la-capitale
    depends_on:
      - db

    # volumes:
    #   - .:/usr/src/app